name: Deploy To Github Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [7]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          yarn install
          yarn test
          yarn lint
          yarn flow
          yarn build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: example/build
          repository-name: gerardburns/gerardburns.github.io
          token: ${{ secrets.DEPLOY_KEY }}
